# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('nomeContato', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('numQuartos', models.IntegerField()),
                ('modelo_fabricacao', models.IntegerField()),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Pousada'), (2, 'Hotel'), (3, 'Albergue'), (4, 'Camping'), (5, 'Flat'), (6, 'Apartamento')])),
                ('categoria', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('Internet', models.BooleanField()),
            ],
        ),
    ]
